---
title: "Accessibility Rules!"
subtitle: "Orientation Week 2025"
author: "Nicole Harms"
format: 
  revealjs: 
    theme: simple
    link-external-newwindow: true
    link-external-icon: true
    logo: logo.jpg
editor: visual
bibliography: references.bib
nocite: |
  @*
---

# Introduction

## What I've been doing... {.center}

-   Researching and learning about accessibility

-   Finding best practices

-   Breaking accessibility down into digestible pieces

-   Creating content for the department

# Accessibility: High Level Overview

## Title II {.center}

-   Refers to Title II of the Americans with Disabilities Act (ADA)

-   Scope of Title II includes public entities such as:

    -   Schools
    -   Colleges
    -   State and local governments
    -   Healthcare providers

-   Don't have to receive funding to fall under the scope of Title II

## Title II {.center}

Serves two main purposes:

-   Prohibits the discrimination of a disabled individual by previously described public entities

-   Requires all individuals be able to benefit from and access their services

::: notes
Disabled does NOT always mean a disability someone was born with! Could also refer to an injury that happened to someone (permanent or not).
:::

## Title II Examples {.center}

-   Elevators/ramps to access all areas of a building

-   Online government forms that anybody could access

-   Allowing service animals

"Accessible" = anyone can access

::: notes
Accessible is easy to think about when it comes to something like a building. Not as easy to conceptualize when it comes to documents or online materials.
:::

## Web Content Accessibility Guidelines (WCAG) {.center style="font-size: 38px"}

-   Department of Justice (DOJ) published a new rule under Title II in April 2024 regarding online accessibility regulations

-   Web content and other digital material must meet WCAG Version 2.1, Level AA standards

    -   Levels range from A to AAA
    -   AAA is highest level of accessibility

-   WCAG are developed by World Wide Web Consortium (W3C)

## WCAG Overview

Each guideline falls into one of four categories of the **POUR** acronym:

-   [**P**]{.underline}erceivable

-   [**O**]{.underline}perable

-   [**U**]{.underline}nderstandable

-   [**R**]{.underline}obust

The POUR acronym is commonly used to recall guidelines. A link to the full list of guidelines is in the "Resources" section of this presentation.

## Perceivable {.center}

"Information and user interface components must be presentable to users in ways they can perceive."

-   Alternative (alt) text

-   Closed captioning/audio transcript

-   Color contrast/schemes

-   Text size and spacing

-   Display orientation

## Operable {.center}

"User interface components and navigation must be operable."

-   Keyboard navigation

-   Keyboard focus is visible

-   Ability to adjust timed content

-   Content is in readable order (focus order)

## Understandable {.center}

"Information and the operation of the user interface must be understandable."

-   No unusual language (slang) is used

-   Abbreviations are explained

-   Webpage navigation is consistent and predictable

-   Input fields provide assistance and error assistance

## Robust {.center}

"Content must be robust enough that it can be interpreted by a wide variety of user agents, including assistive technologies."

-   Elements of a page or document are correctly tagged, labeled, and nested

-   Status messages can be presented to assistive technologies without receiving focus

. . .

*Most* HTML or XML based is considered to have met this criteria.

# Best Practices

## How does this apply to you? {.center}

Your content should be made accessible if:

::: incremental
-   You are distributing it to students digitally

    -   Slides
    -   PDFs
    -   Lecture videos

-   It is a website for your class

-   It will be distributed on our department website for public use
:::

## How does this apply to you? {.center}

Materials that you do not need to make accessible:

-   Digital content provided by a book publisher

    -   Slides
    -   PDFs
    -   Lecture videos

-   Presumed accessible if they're distributed by a publisher

## How does this apply to you? {.center}

Other content

-   External websites used for teaching

    -   YouTube videos should have captions

    -   Use website checkers to ensure basic accessibility

-   Conference presentations (if slides are provided online)

## Common Accessibility "Areas" {.center}

-   Alt text

    -   Concise
    -   Descriptive

-   Keyboard navigation

    -   Can you reach all points on the page?
    -   Can you tell where the keyboard focus is?

-   Links

    -   Make sure link text is descriptive and concise
    -   Use entire email address for link text for emails

## Common Accessibility "Areas" {.center}

-   Document types

    -   HTML based is best
    -   Word and PowerPoint have built in accessibility checks
    -   PDF is generally the hardest to make completely accessible
        -   LaTeX PDFs are not accessible
        -   Adobe Acrobat can add accessibility features to PDFs

-   Overall document/website structure

    -   Headings, layout, etc.

## Common Accessibility "Areas" {.center}

-   Color contrast/schemes

    -   4.5:1 ratio
        -   Large scale text (3:1)
        -   Logos are exempt
    -   Avoid color palettes that are difficult for color blind users

-   Font size/spacing

## Common Accessibility "Areas" {.center}

-   Avoid slang or abbreviations that may be difficult to understand

-   Emojis are OK, but:

    -   Ensure you're using emojis, not emoticons
        -   Emoji: 😁
        -   Emoticon: :)
    -   Use sparingly

## Slide Accessibility {.center}

-   Less is more!

-   Main components to check:

    -   Alternative text
    -   Links
    -   Color contrast
    -   Overall formatting
    -   Keyboard navigation

## Slide Accessibility {.center}

-   In general, HTML based slides are best

    -   Quarto/Revealjs

-   Powerpoint

    -   Has built-in accessibility checker
    -   [PowerPoint Accessibility](https://support.microsoft.com/en-us/office/make-your-powerpoint-presentations-accessible-to-people-with-disabilities-6f7772b2-2f33-4bd2-8ca7-dae3b2b3ef25)

-   Printing slides to a PDF is generally the least accessible

    -   Requires extra steps to make accessible

## Slide Accessibility {.center}

Annotating

-   Annotations made in class are not accessible *if they are saved as images and uploaded digitally*

    -   Alt text should be added ONLY if slides are to be distributed digitally

-   You can still do annotations in class!

## PDF Accessibility {.center}

-   Adobe is essentially the only option

-   Has automatic accessibility checker

-   Can add alt text, document structure tags, etc.

-   Accessibility of a PDF largely depends on how its source document was structured

-   [PDF Accessibility](https://www.adobe.com/acrobat/hub/what-is-an-accessible-pdf.html)

## Graphic Accessibility {.center}

-   Not always possible to make graphics fully accessible

-   Alt text

    -   Useful, but often difficult to fully explain a graphic

    -   Packages like `BrailleR` generate alt text

-   `svg`-based web graphics are a good alternative

    -   Ex: `d3`, `Observable.js`, `Highcharts.js`

-   Accessibility [training](https://srvanderplas.github.io/workshop-graphics-communication/content/03-accessibility.html#fig-olli-penguin) by Dr. VanderPlas

## To summarize... {.center}

-   Make materials accessible within reason

    -   Very hard to make anything 100% accessible

-   There is no "one size fits all"

-   "Accessibility is necessary for some and useful for all."

# Resources

## Guidelines and Checklist {.center}

-   Full list of guidelines: [WCAG Quick Reference](https://www.w3.org/WAI/WCAG22/quickref/?versions=2.1)

-   [Website Accessibility Checklist](https://www.siteimprove.com/blog/ada-title-ii-compliance-checklist/)

    -   Gives good general overview

## Automatic Website Checkers {.center}

-   [IBM Accessibility Checker](https://www.ibm.com/able/toolkit/tools/) extension

    -   False positive rate is high
    -   But, gives a good idea of areas that could be improved

-   [WAVE Web Accessibility Evaluation Tool](https://wave.webaim.org/)

    -   Checks websites for accessibility
    -   Useful tool for external websites for a class

## Canvas {.center}

-   Canvas should now automatically check material accessibility

    -   Works for uploaded files

    -   Not insanely reliant, but gives a good idea of areas to improve

-   YuJa

    -   For lecture recordings, automatically provides closed captioning

## Other Useful Resources {.center}

-   [Repository link](https://github.com/nlharms414/stat218-slides)
-   [Slide website link](https://nlharms414.github.io/stat218-slides/)
-   [Color contrast checker](https://colourcontrast.cc/?background=e7c5cc&foreground=000000)
-   [Accessible Hyperlinks](https://accessibility.oit.ncsu.edu/accessible-hyperlinks/)
-   [Digital Accessibility Toolkit](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.enhancementthemes.ac.uk/docs/ethemes/conference/a-digital-accessibility-toolkit-for-stem-subjects.pdf)

# References

::: {#refs}
:::

# Thanks for joining! Questions?
