---
title: "Section 5.1"
subtitle: "Comparing Two Groups: Categorical Response"
format: 
  revealjs: 
    chalkboard: true
    theme: simple
    link-external-newwindow: true
    link-external-icon: true
    html-math-method: katex
    logo: logo.jpg
    slide-number: true
    include-in-header:
      text: |
        <script src="https://cdn.jsdelivr.net/npm/mermaid@11.12.0/dist/mermaid.min.js"></script>
editor: visual
---

## Section 5.1 Learning Objectives {.center}

-   Understand how a two-way table works.

-   Be able to calculate conditional probability for different levels of the categorical variables.

-   Determine whether or not there may be association based on the conditional probabilities that have been calculated.

-   Understand and be able to calculate relative risk.

# Review

## Variable Types {.center}

-   Explanatory (independent) variable

    -   "Explains" ("independent of") the response variable

-   Response (dependent) variable

    -   "Responds to" ("depends on") the explanatory variable

## Variable Types {.center}

-   Confounding variable

    -   Related to both

-   Association does **NOT** mean causation!

    -   We could always potentially have a confounding variable

## Design Types {.center}

-   Observational study vs. experiment

-   Random sample vs. random assignment

## Random vs. Random {.center}

-   Random sampling = can generalize results

-   No random sampling = cannot generalize results

. . .

-   Random assignment = can draw cause and effect conclusion (experiment)

-   No random assignment = can only draw association conclusion (observational)

## Comparing Two Groups {.center}

-   New research question: Are these two groups different?

-   Compare using explanatory and repsonse variables

-   We can still use our same strength of evidence methods!

    ::: incremental
    -   P-value

    -   Standardized statistic

    -   Confidence intervals
    :::

# Example

## Murderous Nurse {.center style="font-size: 37px"}

For several years in the 1990s, Kristen Gilbert worked as a nurse in the intensive care unit (ICU) of the Veterans Administration Hospital in Northampton, Massachusetts. Over the course of her time there, other nurses came to suspect that she was killing patients by injecting them with the heart stimulant epinephrine. Gilbert was eventually arrested and charged with these murders. Part of the evidence presented against Gilbert at her murder trial was a statistical analysis of [**1,641 eight-hour shifts during the time Gilbert worked in the ICU**.]{.underline} For each of these shifts, [**researchers recorded two variables:whether Gilbert worked on the shift and whether at least one patient died during the shift.**]{.underline}

## Murderous Nurse {.center style="font-size: 38px"}

::::: columns
::: {.column width="50%"}
<br><br>

Let's identify the following:

-   Obsevational units

-   Explanatory variable

-   Response variable

-   Observational study or experiment? Why?
:::

::: {.column width="50%"}
+-----------------------------------------------------------------------+
| Key Info                                                              |
+:=====================================================================:+
| -   1,641 shifts during Gilbert's time at ICU were analyzed           |
|                                                                       |
| -   For each shift it was recorded if:                                |
|                                                                       |
|     -   Gilbert worked the shift                                      |
|                                                                       |
|     -   If at least one person died                                   |
+-----------------------------------------------------------------------+
:::
:::::

## Murderous Nurse {.center}

It was found that Gilbert worked 257 of the 1,641 shifts, and at least one person died during 74 of the 1,641 shifts.

. . .

-   Does this tell us much about an association between Gilbert working and patients dying?

-   Why or why not?

## Murderous Nurse {.center}

Now, out of the 74 shifts where at least one person died, we find that 40 were shifts Gilbert worked, and 34 were not.

. . .

-   Now does this seem like more reasonable evidence?

-   Can we simply compare the numbers 34 and 40?

## Two Way Table {.center}

|  |  |  |  |
|:--:|:--:|:--:|:--:|
|  | **Gilbert worked the shift** | **Gilbert did not work the shift** | **Total shifts** |
| **At least one person died during the shift** | 40 | 34 | 74 |
| **No patient died during the shift** | 217 | 1350 | 1567 |
| **Total shifts** | 257 | 1384 | 1641 |

## Observed statistic? {.center}

-   In a normal scenario, our observed statistic would be:

$$\hat{p}=\frac{74}{1641}$$

AKA:

$$\hat{p}=\frac{Total\:shifts\:a\:patient\:died}{Total\:sample\:size}$$

But, this isn't super helpful!

## Conditional Proportion {.center}

Calculates the probability of success within each [explanatory variable group]{.center}

## Conditional Proportions {.center}

```{mermaid}
flowchart LR
  A(Population: All 8-hr shifts) --> B(Sample: 
                                       n = 1,641 observed shifts)
  B -->|"$${n}_G=257$$"| C("$$\hat{p}_G=\frac{40}{257}=0.156$$")
  B -->|"$${n}_{NG}=1384$$"| D("$$\hat{p}_{NG}=\frac{34}{1384}=0.025$$")
```

-   "G" = Gilbert shift
-   "NG" = Non-Gilbert shift

## Conditional Proportions {.center}

$$\hat{p}_G=\frac{Patient\: died\: a\: shift\: Gilbert\: worked}{Total\: shifts\: Gilbert\: worked}$$
$$=\frac{40}{257}$$
$$=0.156$$

## Conditional Proportions {.center}

$$\hat{p}_{NG}=\frac{Patient\: died\: a\: shift\: Gilbert\: did\: not\: work}{Total\: shifts\: Gilbert\: did\: not\: work}$$
$$=\frac{34}{1384}$$
$$=0.025$$

## A new observed statistic {.center}

What to do with two p-hats? Take the difference!

-   $\hat{p}_G = \frac{40}{257} = 0.156$
-   $\hat{p}_{NG} = \frac{34}{1384} = 0.025$

New observed statistic:

$$\hat{p}_G - \hat{p}_{NG} = 0.156-0.025 = 0.131$$

. . . 

Note: The order in which the p-hats are subtracted does not matter- but it will affect your interpretation

## Interpreting the new p-hat {.center}

::: incremental
-   $\hat{p}_G - \hat{p}_{NG} = 0.131$: "The proportion of deaths was 13.1% higher when Gilbert was working than when she was not working"

-   $\hat{p}_{NG} - \hat{p}_{G} = -0.131$: "The proportion of deaths was 13.1% lower when Gilbert was not working than when she was working"
:::

## Relative Risk {.center}

The ratio between two conditional proportions

-   "How many times as large is the risk of an outcome for one group comparted to another?"

## Relative Risk {.center}

To calculate relative risk, divide the conditional proportions

$$\frac{\hat{p}_G}{\hat{p}_{NG}} = \frac{0.15}{0.025} = 7.5$$

"The proportion of deaths during a Gilbert shift is 7.5 times larger than during a non-Gilbert shift."

. . .

What would we expect relative risk to be if there is no difference between the two groups?

## Drawing Conclusions {.center}

-   Was the difference in proportions surprising? 

-   How about relative risk?

-   What do they tell us in this scenario?

-   What might you report to the jury? 

. . .

"She appears guilty, the difference in proportions was not zero, and the relative risk was higher than 1."

## Drawing Conclusions {.center}

-   Given the scenario, can we say Gilbert *caused* the deaths?

    -   Hint: Think back to chapter 4!
    
-   Come up with an alternative explanation for the difference in proportion between the two groups